//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("OrchestratorApi")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+1b0508dddb52831185169a007dec86f2cbd5e73d")]
[assembly: System.Reflection.AssemblyProductAttribute("OrchestratorApi")]
[assembly: System.Reflection.AssemblyTitleAttribute("OrchestratorApi")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("OrchestratorApi.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

