#!/usr/bin/env bash
# Rebuild docs/common-problems/README.md from each entry's frontmatter.
# Always overwrites; the README is treated as a derived artifact.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
root="$repo_root/docs/common-problems"
index="$root/README.md"

fm_scalar() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { fm = !fm; next }
    fm && $0 ~ "^"key":" {
      sub("^"key":[[:space:]]*", "", $0)
      sub("[[:space:]]*$", "", $0)
      gsub("^\"|\"$", "", $0)
      print
      exit
    }
  ' "$1"
}

# Pull frontmatter `tags: [a, b, c]` into space-separated tokens. Lowercase only.
fm_tags() {
  awk '
    /^---[[:space:]]*$/ { fm = !fm; next }
    fm && /^tags:/ {
      sub(/^tags:[[:space:]]*\[/, "", $0)
      sub(/\][[:space:]]*$/, "", $0)
      gsub(/,/, " ", $0)
      print
      exit
    }
  ' "$1"
}

# Find the latest measure with status `works` for fixed entries; fall back to "see measures.md".
# Convention: a row in measures.md with status `works` and a commit hash in the Outcome column.
fix_ref() {
  measures="$1"
  [ -f "$measures" ] || { printf 'see measures.md\n'; return; }
  ref="$(awk -F'|' '
    /^\|[[:space:]]*works[[:space:]]*\|/ {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $6)
      if ($6 != "") { print $6 }
    }
  ' "$measures" | tail -n 1)"
  if [ -n "$ref" ]; then printf '%s\n' "$ref"; else printf 'see measures.md\n'; fi
}

shopt -s nullglob

declare -a rows_open rows_mitigated rows_fixed rows_archived
declare -A tag_seen

for dir in "$root"/*/; do
  slug="$(basename "$dir")"
  case "$slug" in archive) continue ;; esac
  readme="$dir/README.md"
  [ -f "$readme" ] || continue

  id_v="$(fm_scalar "$readme" id)"
  title_v="$(fm_scalar "$readme" title)"
  status_v="$(fm_scalar "$readme" status)"
  sev_v="$(fm_scalar "$readme" severity)"
  cat_v="$(fm_scalar "$readme" category)"
  fs_v="$(fm_scalar "$readme" first-seen)"
  ls_v="$(fm_scalar "$readme" last-seen)"
  fs_short="${fs_v%%T*}"
  ls_short="${ls_v%%T*}"

  row="| [$id_v]($id_v/) | $title_v | $sev_v | $cat_v | $fs_short | $ls_short |"
  case "$status_v" in
    open)       rows_open+=("$row") ;;
    mitigated)  rows_mitigated+=("$row") ;;
    fixed)
      fix="$(fix_ref "$dir/measures.md")"
      rows_fixed+=("$row $fix |") ;;
    archived)   rows_archived+=("$row") ;;
    *)          rows_open+=("$row") ;;
  esac

  for t in $(fm_tags "$readme"); do
    t_clean="$(printf '%s' "$t" | tr -d ' \t')"
    [ -n "$t_clean" ] && tag_seen["$t_clean"]=1
  done
done

today="$(date -u +%Y-%m-%d)"
tmp="$index.tmp"

{
  printf '# Common Problems Index\n\n'
  printf 'Auto-generated by `scripts/wiki/regenerate-index.sh`. Do not edit manually.\n\n'
  printf 'Last regenerated: %s\n\n' "$today"

  emit_section() {
    title="$1"; shift
    has_fix="$1"; shift
    printf '## %s\n\n' "$title"
    if [ "$#" -eq 0 ]; then
      printf '_None._\n\n'
      return
    fi
    if [ "$has_fix" = "1" ]; then
      printf '| ID | Title | Severity | Category | First seen | Last seen | Fix |\n'
      printf '|---|---|---|---|---|---|---|\n'
    else
      printf '| ID | Title | Severity | Category | First seen | Last seen |\n'
      printf '|---|---|---|---|---|---|\n'
    fi
    printf '%s\n' "$@" | sort
    printf '\n'
  }

  emit_section "Open"      0 "${rows_open[@]+"${rows_open[@]}"}"
  emit_section "Mitigated" 0 "${rows_mitigated[@]+"${rows_mitigated[@]}"}"
  emit_section "Fixed"     1 "${rows_fixed[@]+"${rows_fixed[@]}"}"
  emit_section "Archived"  0 "${rows_archived[@]+"${rows_archived[@]}"}"

  printf '## Tag cloud\n\n'
  if [ "${#tag_seen[@]}" -eq 0 ]; then
    printf '_None._\n'
  else
    cloud=""
    for t in $(printf '%s\n' "${!tag_seen[@]}" | sort); do
      cloud="$cloud\`$t\` "
    done
    printf '%s\n' "${cloud% }"
  fi
} > "$tmp"

mv "$tmp" "$index"
echo "regenerated $index"
