import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, inject, input, signal } from '@angular/core';
import type { TokenSummary } from '../../../features/tokens';
import { JobService } from '../../../services/job.service';

/**
 * Per-project token rollup block. Three rows:
 *
 * 1. **Amounts (real).** Total input / output / cache tokens across all
 *    orchestrator LLM calls on this project, with a per-model breakdown
 *    underneath. These numbers are accurate; they come straight from
 *    the orchestrator's CLI envelopes.
 * 2. **Theoretical API cost (estimate).** What the same tokens would
 *    have cost via Anthropic's API. Carried because it is a useful
 *    comparison and a sanity check, *not* because the user pays it.
 *    The disclaimer line is always shown.
 * 3. **Subscription quota link.** Pointer to the existing CLI Usage
 *    sheet (the 🪙 Usage button in the toolbar) which surfaces the
 *    real billing dimension - the user's Pro / Max plan windows.
 *
 * Mounted by `OrchestratorFeedComponent` (header) and
 * `ProjectDetailComponent` (group). 5s poll while mounted.
 */
@Component({
  selector: 'app-token-summary-block',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (summary(); as s) {
      <section class="tok-sum" data-testid="token-summary">
        <header class="tok-sum__head">
          <h3 class="tok-sum__title">Tokens & cost</h3>
          @if (s.orchestratorLlmCalls > 0) {
            <span class="tok-sum__sub">{{ s.orchestratorLlmCalls }} orchestrator call{{ s.orchestratorLlmCalls === 1 ? '' : 's' }}</span>
          } @else {
            <span class="tok-sum__sub">No orchestrator activity yet.</span>
          }
        </header>

        @if (s.orchestratorLlmCalls > 0) {
          <div class="tok-sum__amounts" data-testid="token-summary-amounts">
            <div class="tok-sum__metric" title="Input tokens sent to the model">
              <span class="tok-sum__metric-num">↑ {{ formatTokens(s.totalInputTokens) }}</span>
              <span class="tok-sum__metric-label">input</span>
            </div>
            <div class="tok-sum__metric" title="Output tokens generated by the model">
              <span class="tok-sum__metric-num">↓ {{ formatTokens(s.totalOutputTokens) }}</span>
              <span class="tok-sum__metric-label">output</span>
            </div>
            @if (s.totalCacheReadTokens > 0) {
              <div class="tok-sum__metric" title="Tokens read from prompt cache (10% of input rate)">
                <span class="tok-sum__metric-num">⚡ {{ formatTokens(s.totalCacheReadTokens) }}</span>
                <span class="tok-sum__metric-label">cache read</span>
              </div>
            }
            @if (s.totalCacheCreationTokens > 0) {
              <div class="tok-sum__metric" title="Tokens written to prompt cache (125% of input rate)">
                <span class="tok-sum__metric-num">+ {{ formatTokens(s.totalCacheCreationTokens) }}</span>
                <span class="tok-sum__metric-label">cache write</span>
              </div>
            }
          </div>

          <div class="tok-sum__cost" data-testid="token-summary-cost">
            <span class="tok-sum__cost-label">Theoretical API cost</span>
            <span class="tok-sum__cost-amount"
                  [class.tok-sum__cost-amount--partial]="!s.allModelsPriced">
              {{ formatUsd(s.estimatedApiCostUsd) }}
              @if (!s.allModelsPriced) { <span class="tok-sum__partial">(partial; some models not priced)</span> }
            </span>
          </div>

          @if (s.byModel.length > 0) {
            <details class="tok-sum__breakdown">
              <summary>Per-model breakdown</summary>
              <table class="tok-sum__table">
                <thead>
                  <tr>
                    <th>Model</th>
                    <th>Calls</th>
                    <th>Input</th>
                    <th>Output</th>
                    <th>API cost</th>
                  </tr>
                </thead>
                <tbody>
                  @for (m of s.byModel; track m.model) {
                    <tr>
                      <td><code>{{ m.model }}</code></td>
                      <td>{{ m.calls }}</td>
                      <td>{{ formatTokens(m.inputTokens) }}</td>
                      <td>{{ formatTokens(m.outputTokens) }}</td>
                      <td>
                        @if (m.modelPriced) {
                          {{ formatUsd(m.estimatedApiCostUsd) }}
                        } @else {
                          <span class="tok-sum__na">n/a</span>
                        }
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </details>
          }
        }

        <p class="tok-sum__disclaimer">{{ s.disclaimer }}</p>
      </section>
    }
  `,
  styles: [`
    :host { display: block; }
    .tok-sum {
      padding: 10px 14px;
      border-radius: 8px;
      border: 1px solid rgba(255, 255, 255, 0.10);
      background: rgba(15, 23, 42, 0.45);
      margin-bottom: 12px;
    }
    .tok-sum__head {
      display: flex;
      align-items: baseline;
      gap: 10px;
      margin-bottom: 8px;
    }
    .tok-sum__title {
      margin: 0;
      font-size: 0.78rem;
      color: rgba(255,255,255,0.55);
      text-transform: uppercase;
      letter-spacing: 0.06em;
    }
    .tok-sum__sub { color: rgba(255,255,255,0.55); font-size: 0.75rem; }
    .tok-sum__amounts {
      display: flex;
      flex-wrap: wrap;
      gap: 14px;
      margin-bottom: 8px;
    }
    .tok-sum__metric {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      cursor: help;
    }
    .tok-sum__metric-num {
      color: #cdd6f4;
      font-size: 1.05rem;
      font-weight: 700;
      font-variant-numeric: tabular-nums;
    }
    .tok-sum__metric-label {
      color: rgba(255,255,255,0.50);
      font-size: 0.66rem;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }

    .tok-sum__cost {
      display: flex;
      align-items: baseline;
      gap: 8px;
      padding: 6px 8px;
      border-radius: 6px;
      background: rgba(249, 226, 175, 0.06);
      border: 1px dashed rgba(249, 226, 175, 0.30);
      margin-bottom: 8px;
    }
    .tok-sum__cost-label {
      color: rgba(249, 226, 175, 0.85);
      font-size: 0.78rem;
    }
    .tok-sum__cost-amount {
      color: #fcd34d;
      font-size: 1.0rem;
      font-weight: 700;
      font-variant-numeric: tabular-nums;
    }
    .tok-sum__cost-amount--partial { color: #fde68a; }
    .tok-sum__partial { font-weight: 400; font-size: 0.74rem; color: rgba(255,255,255,0.50); }

    .tok-sum__breakdown { margin-bottom: 8px; }
    .tok-sum__breakdown summary {
      cursor: pointer;
      color: rgba(255,255,255,0.60);
      font-size: 0.78rem;
      user-select: none;
    }
    .tok-sum__breakdown summary:hover { color: #cdd6f4; }
    .tok-sum__table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 6px;
      font-size: 0.78rem;
    }
    .tok-sum__table th, .tok-sum__table td {
      padding: 4px 6px;
      text-align: left;
      border-bottom: 1px solid rgba(255,255,255,0.06);
      font-variant-numeric: tabular-nums;
    }
    .tok-sum__table th {
      color: rgba(255,255,255,0.50);
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      font-size: 0.66rem;
    }
    .tok-sum__table td code {
      font-size: 0.74rem;
      background: rgba(255,255,255,0.06);
      padding: 1px 4px;
      border-radius: 3px;
    }
    .tok-sum__na { color: rgba(255,255,255,0.40); font-style: italic; }

    .tok-sum__disclaimer {
      margin: 4px 0 0;
      font-size: 0.74rem;
      color: rgba(255,255,255,0.55);
      line-height: 1.4;
      font-style: italic;
    }
  `]
})
export class TokenSummaryBlockComponent implements OnInit, OnDestroy {
  readonly projectName = input.required<string>();

  private readonly jobService = inject(JobService);
  readonly summary = signal<TokenSummary | null>(null);
  private pollTimer: ReturnType<typeof setInterval> | null = null;

  ngOnInit(): void {
    this.refresh();
    this.pollTimer = setInterval(() => this.refresh(), 5_000);
  }

  ngOnDestroy(): void {
    if (this.pollTimer != null) clearInterval(this.pollTimer);
    this.pollTimer = null;
  }

  refresh(): void {
    this.jobService.getTokenSummary(this.projectName()).subscribe({
      next: (s) => this.summary.set(s),
      error: () => { /* keep last value */ }
    });
  }

  /** "12,345" -> "12.3K" so the metric strip stays compact. */
  formatTokens(n: number): string {
    if (n < 1_000) return n.toString();
    if (n < 1_000_000) return (n / 1_000).toFixed(n < 10_000 ? 1 : 0) + 'K';
    return (n / 1_000_000).toFixed(n < 10_000_000 ? 2 : 1) + 'M';
  }

  /** Two decimal places below $10, three below $1, four below $0.10. */
  formatUsd(n: number): string {
    if (!Number.isFinite(n)) return '$0.00';
    if (n === 0) return '$0.00';
    if (n < 0.1) return '$' + n.toFixed(4);
    if (n < 1)   return '$' + n.toFixed(3);
    return '$' + n.toFixed(2);
  }
}
